[http.routers]
  [http.routers.grafana]
    rule = "Host(`brew.galgo.cat`)"
    service = "grafana"
    middlewares = ["grafana-redirectregex"]
    [http.routers.grafana.tls]
      certResolver = "le"

[http.services]
  [http.services.grafana.loadBalancer]
    [[http.services.grafana.loadBalancer.servers]]
      url = "http://grafana:3000/"

[http.middlewares]
  [http.middlewares.grafana-redirectregex.redirectRegex]
    regex = "^https://brew.galgo.cat/$"
    replacement = "${0}d/k/brew?orgId=1&refresh=10s&kiosk"
